version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: bustracksv-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bustracksv-network

  # Servicio opcional para administrar la base de datos
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bustracksv-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@bustracksv.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bustracksv-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bustracksv-network:
    driver: bridge
